### ISSUE TITLE
Vẽ Prototype cho toàn Web

### ISSUE THREAD

**Issue by nguyentantrung2000** [Runway-Club/Runway-CV-Builder#11]
Một số thông tin của task

1.Vẽ bằng figma.
2.Các màu sắc phải đồng bộ ( màu chủ đạo Runway).
3.Phải đầy đủ bố cục của một trang web.
Yêu cầu:

1.giao diện đẹp, hợp lý
2.deadline 11:59 PM 22/6/2021

**Comment by nguyentantrung2000** [comment]
Đây là kết quả của mình và @nguyenxuanquang6789 và @trungdoublelift 
https://www.figma.com/file/RFSCGYxQXF3YNTFKisl2gr/Untitled?node-id=0%3A1

**Comment by AmbroseNTK** [comment]
Có một số vấn đề trong template như sau:
1. Các component trong UI chưa có sự thống nhất
2. Màu sắc, chọn lại từ bảng màu
3. Các giao diện cần đơn giản hóa, tập trung vào chức năng chính yếu của người dùng. Ko thêm thắt quảng cáo,...

Vì vậy, các bạn cần thống nhất giao diện với một triết lý thiết kế duy nhất.
Mình thấy, trong trường hợp này, phù hợp hơn hẳn là:
https://eva.design/

Các bạn thử áp dụng xem sao

**Comment by AmbroseNTK** [comment]
Nếu eva khó quá có thể dùng UI Kit này nhé các bạn
https://evergreen.segment.com/

**Comment by nguyentantrung2000** [comment]
Dạ tụi em sẽ tiếp thu ý kiến này và thay đổi. Rất cảm ơn anh ạ.

**Comment by AmbroseNTK** [comment]
a gửi thêm
https://atomizecode.com/

**Comment by nguyentantrung2000** [comment]
Sau khi tiếp thu ý kiến thì tụi mình đã có sự thay đổi lại, mời mọi người xem qua ạ.
https://www.figma.com/file/RFSCGYxQXF3YNTFKisl2gr/Untitled?node-id=0%3A1

**Comment by AmbroseNTK** [comment]
Mình có một số nhận xét sau:
1. Đã có tính thống nhất ở các component khác nhau.
2. Màu sắc, bố cục ổn
Tuy nhiên, lưu ý: đây chỉ là Prototype LoFi. Vì vậy, khi triển khai các chức năng chi tiết, cần có prototype riêng cho chức năng đó

**Comment by nguyentantrung2000** [comment]
Mình xin cảm ơn nhận xét và đóng góp. Vì một số trục trặc cũng như để hoàn thiện bản Prototype hoàn chỉnh hơn thì mình sẽ nới rộng deadline ra cho đến 11:59 PM 25/6/2021

**Comment by nguyentantrung2000** [comment]
Hiện tại thì mình đã thêm tính năng đổi màu cho cv cũng như các luồng chạy của prototype mọi người có thể xem qua và chúng ta sẽ bắt đầu project sau khi duyệt prototype lần cuối https://www.figma.com/file/RFSCGYxQXF3YNTFKisl2gr/Untitled?node-id=0%3A1
