### ISSUE TITLE
Tạo giao diện trang xem các loại CV mẫu

### ISSUE THREAD

**Issue by nguyentantrung2000** [Runway-Club/Runway-CV-Builder#15]
Yêu cầu:
Màu sắc phải đúng như trong figma(các màu chủ đạo)
Đúng các bố cục figma
Có thể dùng các nút để lướt qua lại xem CV
deadline 11:59 PM 30/7/2021

**Comment by nguyentantrung2000** [comment]
Sau khi xem bài của bạn thì nó vẫn còn bị bug 1 số tính năng ở các nút trái , phải để xem CV . Bạn vui lòng chỉnh sửa lại nhé

**Comment by trungdoublelift** [comment]
Tôi đã fix  bug xong và đã tạo pull request. Bạn kiểm tra giúp mình nhá :D

**Comment by nguyentantrung2000** [comment]
Sau khi kiểm trra thì các chức năng của bạn đã hoàn thành.
