### ISSUE TITLE
Tạo giao diện để xem các loại CV đã làm ( của User)

### ISSUE THREAD

**Issue by nguyentantrung2000** [Runway-Club/Runway-CV-Builder#16]
Yêu cầu:
Màu sắc phải đúng như trong figma(các màu chủ đạo)
Đúng các bố cục figma
Có thể dùng các nút để lướt qua lại xem CV
deadline 11:59 PM 30/7/2021

**Comment by trungdoublelift** [comment]
Tôi đã hoàn thành task của mình và đã tạo pull request.

**Comment by nguyentantrung2000** [comment]
sau khi check và test thì  bạn đã hoàn thành task
