### ISSUE TITLE
Tạo giao diện dialog skill , Education , School, Employments của Trang chỉnh sửa CV

### ISSUE THREAD

**Issue by nguyentantrung2000** [Runway-Club/Runway-CV-Builder#25]
Yêu cầu của task:
Thiết kế phù hợp đúng bố cục figma
Có thể ấn chọn và thêm các options
.deadline 11:59 PM 30/7/2021

**Comment by nguyenxuanquang6789** [comment]
Tôi đã hoàn thành xong task được giao, bạn hãy xem xét pull request của mình.

**Comment by nguyentantrung2000** [comment]
Sau khi xem xét thì có lẽ bạn đã nhầm lẫn giữa "page" và "component " nên đã làm sai task yêu cầu. Bạn vui lòng làm lại và hoàn thành trước deadline nhé !

**Comment by nguyenxuanquang6789** [comment]
Tôi đã chỉnh sửa lại, bạn xem xét về pull request giúp mình.
