### ISSUE TITLE
Tạo giao diện trang landing page ( của a Tâm )

### ISSUE THREAD

**Issue by nguyentantrung2000** [Runway-Club/Runway-CV-Builder#40]
Yêu cầu:
Giao diện hợp lý , phù hợp đúng theo bố cục figma

**Comment by nguyenxuanquang6789** [comment]
Tôi đã hoàn thành xong task. Bạn xem xét pull request nhé !

**Comment by nguyentantrung2000** [comment]
Sau khi xem xét bạn đã làm đúng và hoàn thành task yêu cầu.
