### ISSUE TITLE
Tạo thuộc tính cho 1 user : tài khoản , mật khẩu , tên (full name) , CV List ( các cv mẫu đã tạo) , List tên các doanh nghiệp đã nộp đơn.

### ISSUE THREAD

**Issue by nguyentantrung2000** [Runway-Club/Runway-CV-Builder#50]
Yêu cầu:
-Phải đầy đủ các trường đã yêu cầu
-Deadline 11:59PM 5/8/2021

**Comment by trungdoublelift** [comment]
Tôi đã hoàn thành xong task và đã tạo pull request, check giùm tôi nhé :D

**Comment by nguyentantrung2000** [comment]
Sau khi xem xét bạn đã làm rất tốt và hoàn thành task
