### ISSUE TITLE
Chức năng thêm xoá sửa trong CV List

### ISSUE THREAD

**Issue by nguyentantrung2000** [Runway-Club/Runway-CV-Builder#71]
Yêu cầu:
Phải xoá được , và thêm đc CV theo ý của user
Deadline 11:59PM 12/8/2021

**Comment by trungdoublelift** [comment]
Tôi đã hoàn thành task của mình và đã tạo pull request

**Comment by nguyentantrung2000** [comment]
Sau khi kiểm tra bạn đã hoàn thành xong  task
