### ISSUE TITLE
Ràng buộc input của User trong create CV

### ISSUE THREAD

**Issue by nguyentantrung2000** [Runway-Club/Runway-CV-Builder#73]
Yêu cầu:
Ràng buộc tất cả các input (Nếu cần thiết) trong trang create CV
Deadline 11:59PM 12/8/2021

**Comment by nguyenxuanquang6789** [comment]
Tôi chưa hoàn thành task được giao. Lí do:
- Tôi đã tìm hiểu về cách Validate input của User trên UI thì các cách được chỉ phải sử dụng Class, Extend, Export,... thì hiện tại PJ chưa sử dụng Class
- Tôi đã thử bằng cách Validate "chay" nhưng trong code bị lỗi, khi sửa lại theo recommend của code thì cũng không chạy được và bị lỗi.
Vì thế task của tôi chậm tiến độ nên kéo theo task của @trungdoublelift  "Lưu dữ liệu người dùng nhập trong input create CV bằng firebase" bị chậm tiến độ, vì thế tôi xin gia hạn deadline của task để làm thêm.

**Comment by nguyentantrung2000** [comment]
Vì task của bạn cũng là một task khó và luôn cập nhật song song với project nên mình sẽ chỉnh deadline của bạn và @trungdoublelift . Cảm ơn bạn vì sự đóng góp

**Comment by nguyentantrung2000** [comment]
Deadline:  11:59PM 18/8/2021

**Comment by nguyentantrung2000** [comment]
Tôi xin phép để được assgin vào và trợ giúp bạn task này nhé.

**Comment by nguyenxuanquang6789** [comment]
Tôi đã hoàn thành xong task, bạn xem xét pull request giúp mình

**Comment by nguyentantrung2000** [comment]
Sau khi xem xét thì thấy bạn đã hoàn thành task, cảm ơn sự đóng góp của bạn nhé.
